services:
  mongo:
    command: ["--replSet", "rs0", "--bind_ip_all"]
    image: mongo:8.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./init-replica.js:/docker-entrypoint-initdb.d/init-replica.js:ro
      - mongo_data:/data/db

  jena-fuseki:
    image: stain/jena-fuseki
    container_name: jena-fuseki
    platform: linux/amd64
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=admin
    volumes:
      - ./init-replica.js:/docker-entrypoint-initdb.d/init-replica.js:ro
      - jena_data:/fuseki
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "${MINIO_API_PORT}:9000"    
      - "${MINIO_CONSOLE_PORT}:9001" 
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      # Rellena estas dos si luego pones dominio y TLS
      # MINIO_SERVER_URL: https://s3.tudominio.com
      # MINIO_BROWSER_REDIRECT_URL: https://console.tudominio.com
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
volumes:
  mongo_data:  
  jena_data:
  minio_data:
